/**
 * @gao/ui — Theme Engine
 *
 * Generates CSS custom properties from a GaoThemeConfig.
 * Auto-derives secondary, accent, and dark mode variants
 * from a single primary HSL color.
 *
 * Default: GAO Corporate (hsl(215, 70%, 40%) — dark blue)
 *
 * @since 0.6.0
 */

import type { GaoThemeConfig, GaoHSLColor, GaoThemePresetName } from './theme-types.js';
import { GAO_THEMES } from './theme-presets.js';

// ─── Helper Functions ────────────────────────────────────────

/**
 * Format an HSL color to CSS string.
 */
function hsl(color: GaoHSLColor): string {
    return `hsl(${color.h}, ${color.s}%, ${color.l}%)`;
}

/**
 * Create an HSL variant with a different lightness.
 */
function withLightness(color: GaoHSLColor, l: number): string {
    return `hsl(${color.h}, ${color.s}%, ${l}%)`;
}

/**
 * Auto-generate a secondary color by shifting hue +30°.
 */
function defaultSecondary(primary: GaoHSLColor): GaoHSLColor {
    return { h: (primary.h + 30) % 360, s: primary.s, l: primary.l + 10 };
}

/**
 * Auto-generate an accent color by shifting hue +40°.
 */
function defaultAccent(primary: GaoHSLColor): GaoHSLColor {
    return { h: (primary.h + 40) % 360, s: Math.max(primary.s - 20, 20), l: primary.l + 10 };
}

/**
 * Map radius preset to CSS values.
 */
function radiusValues(preset: GaoThemeConfig['radius']): Record<string, string> {
    switch (preset) {
        case 'none': return { sm: '0', md: '0', lg: '0', xl: '0', '2xl': '0', full: '0' };
        case 'sm': return { sm: '0.25rem', md: '0.375rem', lg: '0.5rem', xl: '0.625rem', '2xl': '0.75rem', full: '9999px' };
        case 'lg': return { sm: '0.5rem', md: '0.75rem', lg: '1rem', xl: '1.25rem', '2xl': '1.75rem', full: '9999px' };
        case 'full': return { sm: '9999px', md: '9999px', lg: '9999px', xl: '9999px', '2xl': '9999px', full: '9999px' };
        case 'md':
        default: return { sm: '0.375rem', md: '0.5rem', lg: '0.75rem', xl: '1rem', '2xl': '1.5rem', full: '9999px' };
    }
}

/**
 * Map density preset to spacing multiplier description.
 */
function densityValues(preset: GaoThemeConfig['density']): Record<string, string> {
    switch (preset) {
        case 'compact': return { '1': '0.2rem', '2': '0.375rem', '3': '0.5rem', '4': '0.75rem', '6': '1rem', '8': '1.5rem' };
        case 'spacious': return { '1': '0.375rem', '2': '0.625rem', '3': '1rem', '4': '1.25rem', '6': '2rem', '8': '2.5rem' };
        case 'comfortable':
        default: return { '1': '0.25rem', '2': '0.5rem', '3': '0.75rem', '4': '1rem', '6': '1.5rem', '8': '2rem' };
    }
}

// ─── Core Engine ─────────────────────────────────────────────

/**
 * Generate CSS custom properties from a theme configuration.
 *
 * @param config - Theme config or preset name string
 * @returns CSS string with :root variables
 */
export function generateThemeCSS(config: GaoThemeConfig): string {
    const { colors, radius = 'md', density = 'comfortable', fontFamily } = config;
    const primary = colors.primary;
    const secondary = colors.secondary ?? defaultSecondary(primary);
    const accent = colors.accent ?? defaultAccent(primary);

    const r = radiusValues(radius);
    const d = densityValues(density);

    let css = `
/* ═══════════════════════════════════════════════════════════
 * GAO Theme: ${config.name}
 * Primary: hsl(${primary.h}, ${primary.s}%, ${primary.l}%)
 * Generated by GAO Theme Engine v0.6.0
 * ═══════════════════════════════════════════════════════════ */

:root {
  /* ── Primary ── */
  --gao-primary-h: ${primary.h};
  --gao-primary-s: ${primary.s}%;
  --gao-primary-l: ${primary.l}%;
  --gao-primary: ${hsl(primary)};
  --gao-primary-light: ${withLightness(primary, Math.min(primary.l + 15, 85))};
  --gao-primary-dark: ${withLightness(primary, Math.max(primary.l - 10, 15))};
  --gao-primary-bg: ${withLightness(primary, 96)};

  /* ── Secondary ── */
  --gao-secondary: ${hsl(secondary)};

  /* ── Accent ── */
  --gao-accent-h: ${accent.h};
  --gao-accent-s: ${accent.s}%;
  --gao-accent-l: ${accent.l}%;
  --gao-accent: ${hsl(accent)};

  /* ── Semantic (auto-defaults) ── */
  --gao-success: ${colors.success ? hsl(colors.success) : 'hsl(152, 60%, 42%)'};
  --gao-success-bg: ${colors.success ? withLightness(colors.success, 95) : 'hsl(152, 60%, 95%)'};
  --gao-warning: ${colors.warning ? hsl(colors.warning) : 'hsl(38, 92%, 50%)'};
  --gao-warning-bg: ${colors.warning ? withLightness(colors.warning, 95) : 'hsl(38, 92%, 95%)'};
  --gao-danger: ${colors.danger ? hsl(colors.danger) : 'hsl(350, 72%, 52%)'};
  --gao-danger-bg: ${colors.danger ? withLightness(colors.danger, 96) : 'hsl(350, 72%, 96%)'};
  --gao-info: ${colors.info ? hsl(colors.info) : 'hsl(200, 80%, 50%)'};
  --gao-info-bg: ${colors.info ? withLightness(colors.info, 96) : 'hsl(200, 80%, 96%)'};

  /* ── Radius ── */
  --gao-radius-sm: ${r.sm};
  --gao-radius-md: ${r.md};
  --gao-radius-lg: ${r.lg};
  --gao-radius-xl: ${r.xl};
  --gao-radius-2xl: ${r['2xl']};
  --gao-radius-full: ${r.full};

  /* ── Density (Spacing Override) ── */
  --gao-space-1: ${d['1']};
  --gao-space-2: ${d['2']};
  --gao-space-3: ${d['3']};
  --gao-space-4: ${d['4']};
  --gao-space-6: ${d['6']};
  --gao-space-8: ${d['8']};${fontFamily ? `\n\n  /* ── Font Override ── */\n  --gao-font-sans: '${fontFamily}', system-ui, -apple-system, sans-serif;` : ''}
}

/* ── Auto Dark Mode Overrides ── */
[data-theme="dark"] {
  --gao-primary-bg: ${withLightness(primary, 14)};
}`;

    return css;
}

/**
 * Generate CSS and wrap in a `<style>` tag.
 *
 * Accepts either a preset name string or a full theme config object.
 *
 * @param configOrName - GaoThemeConfig object or preset name string
 * @returns HTML `<style>` element with theme CSS
 */
export function injectTheme(configOrName: GaoThemeConfig | GaoThemePresetName): string {
    let config: GaoThemeConfig;

    if (typeof configOrName === 'string') {
        const preset = GAO_THEMES[configOrName];
        if (!preset) {
            throw new Error(`Unknown theme preset: "${configOrName}". Available presets: ${Object.keys(GAO_THEMES).join(', ')}`);
        }
        config = preset;
    } else {
        config = configOrName;
    }

    const css = generateThemeCSS(config);
    return `<style id="gao-theme-${config.name}">\n${css}\n</style>`;
}
